name: Dagger/tests

on:
  push:
  workflow_dispatch:
    
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: andreaswachs/go-dagger@v1
        with:
          working-directory: pipelines
          name: "Dagger: CI/CD"
